 // <auto-generated />
using System;
using KitchenAidAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenAidAI.Migrations
{
    [DbContext(typeof(KitchenAidDbContext))]
    [Migration("20260505144157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KitchenAidAI.Models.ChatMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("datumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("message")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("response")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("tip")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Frizider", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("azurirano")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Frizideri");
                });

            modelBuilder.Entity("KitchenAidAI.Models.KorakRecepta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("opis")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("receptId")
                        .HasColumnType("int");

                    b.Property<int>("redniBroj")
                        .HasColumnType("int");

                    b.Property<double>("trajanje")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("receptId");

                    b.ToTable("KoraciRecepta");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Kuharica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("naziv")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Kuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Namirnica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("friziderId")
                        .HasColumnType("int");

                    b.Property<int>("kategorija")
                        .HasColumnType("int");

                    b.Property<double>("kolicinaUFrizideru")
                        .HasColumnType("double");

                    b.Property<int>("mjera")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.HasIndex("friziderId");

                    b.ToTable("Namirnice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Recept", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("brojPorcija")
                        .HasColumnType("int");

                    b.Property<DateTime>("datumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("naziv")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("tezina")
                        .HasColumnType("int");

                    b.Property<double>("vrijemeKuhanja")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Recepti");
                });

            modelBuilder.Entity("KitchenAidAI.Models.ReceptKuharica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("kuharicaId")
                        .HasColumnType("int");

                    b.Property<int>("receptId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("kuharicaId");

                    b.HasIndex("receptId", "kuharicaId")
                        .IsUnique();

                    b.ToTable("ReceptKuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("preferencijaPrehrane")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KitchenAidAI.Models.ChatMessage", b =>
                {
                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithMany("chatPoruke")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Frizider", b =>
                {
                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithOne("frizider")
                        .HasForeignKey("KitchenAidAI.Models.Frizider", "userId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.KorakRecepta", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Recept", "recept")
                        .WithMany("koraci")
                        .HasForeignKey("receptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recept");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Kuharica", b =>
                {
                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithOne("kuharica")
                        .HasForeignKey("KitchenAidAI.Models.Kuharica", "userId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Namirnica", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Frizider", "frizider")
                        .WithMany("namirnice")
                        .HasForeignKey("friziderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KitchenAidAI.Models.NutritivnaVrijednost", "nutritivnaVrijednost", b1 =>
                        {
                            b1.Property<int>("Namirnicaid")
                                .HasColumnType("int");

                            b1.Property<double>("kalorije")
                                .HasColumnType("double");

                            b1.Property<double>("masti")
                                .HasColumnType("double");

                            b1.Property<double>("proteini")
                                .HasColumnType("double");

                            b1.Property<double>("sol")
                                .HasColumnType("double");

                            b1.Property<double>("ugljikohidrati")
                                .HasColumnType("double");

                            b1.Property<double>("vlakna")
                                .HasColumnType("double");

                            b1.HasKey("Namirnicaid");

                            b1.ToTable("Namirnice");

                            b1.WithOwner()
                                .HasForeignKey("Namirnicaid");
                        });

                    b.Navigation("frizider");

                    b.Navigation("nutritivnaVrijednost");
                });

            modelBuilder.Entity("KitchenAidAI.Models.ReceptKuharica", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Kuharica", "kuharica")
                        .WithMany("receptKuharice")
                        .HasForeignKey("kuharicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAidAI.Models.Recept", "recept")
                        .WithMany("receptKuharice")
                        .HasForeignKey("receptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kuharica");

                    b.Navigation("recept");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Frizider", b =>
                {
                    b.Navigation("namirnice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Kuharica", b =>
                {
                    b.Navigation("receptKuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Recept", b =>
                {
                    b.Navigation("koraci");

                    b.Navigation("receptKuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.User", b =>
                {
                    b.Navigation("chatPoruke");

                    b.Navigation("frizider");

                    b.Navigation("kuharica");
                });
#pragma warning restore 612, 618
        }
    }
}
