// <auto-generated />
using System;
using KitchenAidAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenAidAI.Migrations
{
    [DbContext(typeof(KitchenAidDbContext))]
    [Migration("20260608144843_AddIdentitySchema")]
    partial class AddIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KitchenAidAI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("authProvider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("authProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("datumRodenja")
                        .HasColumnType("date");

                    b.Property<int?>("friziderid")
                        .HasColumnType("int");

                    b.Property<string>("ime")
                        .HasColumnType("longtext");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("kuharicaid")
                        .HasColumnType("int");

                    b.Property<int>("preferencijaPrehrane")
                        .HasColumnType("int");

                    b.Property<string>("prezime")
                        .HasColumnType("longtext");

                    b.Property<string>("zemlja")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("friziderid");

                    b.HasIndex("kuharicaid");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KitchenAidAI.Models.ChatMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datumKreiranja");

                    b.Property<string>("message")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("response")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("tip")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("userId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id");

                    b.HasIndex("naziv")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Datoteka", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("contentType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("naziv")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("putanja")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<long>("velicina")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("userId", "isDeleted", "kreirano");

                    b.ToTable("Datoteke");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Frizider", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("azurirano")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Frizideri");
                });

            modelBuilder.Entity("KitchenAidAI.Models.KorakRecepta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("opis")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("receptId")
                        .HasColumnType("int");

                    b.Property<int>("redniBroj")
                        .HasColumnType("int");

                    b.Property<double>("trajanje")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("receptId");

                    b.ToTable("KoraciRecepta");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Kuharica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("naziv")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Kuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Namirnica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("friziderId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("kategorija")
                        .HasColumnType("int");

                    b.Property<double>("kolicinaUFrizideru")
                        .HasColumnType("double");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("mjera")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.HasIndex("friziderId");

                    b.ToTable("Namirnice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Recept", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("brojPorcija")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datumKreiranja");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("tezina")
                        .HasColumnType("int");

                    b.Property<double>("vrijemeKuhanja")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Recepti");
                });

            modelBuilder.Entity("KitchenAidAI.Models.ReceptKuharica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("kuharicaId")
                        .HasColumnType("int");

                    b.Property<int>("receptId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("kuharicaId");

                    b.HasIndex("receptId", "kuharicaId")
                        .IsUnique();

                    b.ToTable("ReceptKuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("authProvider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("authProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("datumRodenja")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ime")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("passwordHash")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("preferencijaPrehrane")
                        .HasColumnType("int");

                    b.Property<string>("prezime")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("zemlja")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KitchenAidAI.Models.AppUser", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Frizider", "frizider")
                        .WithMany()
                        .HasForeignKey("friziderid");

                    b.HasOne("KitchenAidAI.Models.Kuharica", "kuharica")
                        .WithMany()
                        .HasForeignKey("kuharicaid");

                    b.Navigation("frizider");

                    b.Navigation("kuharica");
                });

            modelBuilder.Entity("KitchenAidAI.Models.ChatMessage", b =>
                {
                    b.HasOne("KitchenAidAI.Models.AppUser", null)
                        .WithMany("chatPoruke")
                        .HasForeignKey("AppUserId");

                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithMany("chatPoruke")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Datoteka", b =>
                {
                    b.HasOne("KitchenAidAI.Models.AppUser", null)
                        .WithMany("datoteke")
                        .HasForeignKey("AppUserId");

                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithMany("datoteke")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Frizider", b =>
                {
                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithOne("frizider")
                        .HasForeignKey("KitchenAidAI.Models.Frizider", "userId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.KorakRecepta", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Recept", "recept")
                        .WithMany("koraci")
                        .HasForeignKey("receptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recept");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Kuharica", b =>
                {
                    b.HasOne("KitchenAidAI.Models.User", "user")
                        .WithOne("kuharica")
                        .HasForeignKey("KitchenAidAI.Models.Kuharica", "userId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("user");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Namirnica", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Frizider", "frizider")
                        .WithMany("namirnice")
                        .HasForeignKey("friziderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KitchenAidAI.Models.NutritivnaVrijednost", "nutritivnaVrijednost", b1 =>
                        {
                            b1.Property<int>("Namirnicaid")
                                .HasColumnType("int");

                            b1.Property<double>("kalorije")
                                .HasColumnType("double");

                            b1.Property<double>("masti")
                                .HasColumnType("double");

                            b1.Property<double>("proteini")
                                .HasColumnType("double");

                            b1.Property<double>("sol")
                                .HasColumnType("double");

                            b1.Property<double>("ugljikohidrati")
                                .HasColumnType("double");

                            b1.Property<double>("vlakna")
                                .HasColumnType("double");

                            b1.HasKey("Namirnicaid");

                            b1.ToTable("Namirnice");

                            b1.WithOwner()
                                .HasForeignKey("Namirnicaid");
                        });

                    b.Navigation("frizider");

                    b.Navigation("nutritivnaVrijednost");
                });

            modelBuilder.Entity("KitchenAidAI.Models.ReceptKuharica", b =>
                {
                    b.HasOne("KitchenAidAI.Models.Kuharica", "kuharica")
                        .WithMany("receptKuharice")
                        .HasForeignKey("kuharicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAidAI.Models.Recept", "recept")
                        .WithMany("receptKuharice")
                        .HasForeignKey("receptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kuharica");

                    b.Navigation("recept");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("KitchenAidAI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("KitchenAidAI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenAidAI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("KitchenAidAI.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenAidAI.Models.AppUser", b =>
                {
                    b.Navigation("chatPoruke");

                    b.Navigation("datoteke");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Frizider", b =>
                {
                    b.Navigation("namirnice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Kuharica", b =>
                {
                    b.Navigation("receptKuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.Recept", b =>
                {
                    b.Navigation("koraci");

                    b.Navigation("receptKuharice");
                });

            modelBuilder.Entity("KitchenAidAI.Models.User", b =>
                {
                    b.Navigation("chatPoruke");

                    b.Navigation("datoteke");

                    b.Navigation("frizider");

                    b.Navigation("kuharica");
                });
#pragma warning restore 612, 618
        }
    }
}
